services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    volumes:
      - open-webui-data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  # Optional: MCP Proxy Server for tools
  mcp-proxy:
    build:
      context: ./mcp-proxy
      dockerfile: Dockerfile
    container_name: mcp-proxy
    ports:
      - "8000:8000"
    volumes:
      - ./mcp-proxy/mcp-config.json:/app/config/mcp-config.json
    restart: always
    profiles:
      - tools

volumes:
  open-webui-data:
    name: open-webui-data
