version: '3.8'

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "${OPENWEBUI_PORT:-3000}:8080"
    volumes:
      - /volume1/docker/openwebui/data:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    networks:
      - openwebui_network

  mcp-proxy:
    build:
      context: ./mcp-proxy
      dockerfile: Dockerfile
    container_name: mcp-proxy
    ports:
      - "${MCP_PROXY_PORT:-8001}:8001"
    volumes:
      - /volume1/docker/openwebui/config/mcp-config.json:/app/config/mcp-config.json
    restart: always
    profiles:
      - tools
    networks:
      - openwebui_network

networks:
  openwebui_network:
    driver: bridge
